### ISSUE TITLE
Errors in Arduino Alpha < A.S.>

### ISSUE THREAD

**Issue by FrankOcean11** [arduino-org/ArduinoStudio#1]
The ArduinoStudios is giving me a error saying:Command failed: C:\Users\Franks\AppData\Local\Temp\build1441644299986\MPU6050_Tx.cpp:16:18: fatal error: Wire.h: No such file or directory #include "Wire.h" ^ compilation terminated.

(let me add a side note that this new error just occur while at first it was giving errors about SPI now is about Wire when Wire is in there as well)

in the regular IDE i dont get this issue but in the Alpha/ArduinoStudios i do, any fix for this?

**Comment by quasto** [comment]
Hi @FrankOcean11,
thank you for reporting this issue. 
Could you tell us which version of Arduino Studio are you using? board? OS? Could you give us some more informations?
thank you

**Comment by FrankOcean11** [comment]
ver3 no board just verifying code not uploading.
win 8.1

**Comment by sebba** [comment]
Hi @FrankOcean11 ,
Thanks alot for your report
I've looked at your bug: unfortunately i can't suggest you a quick fix, we'll fix it in the next release out in the next weeks.

Sorry for the wait.

**Comment by FrankOcean11** [comment]
dam! thanks tho i look forward to the new update Sebba, by the way you know
how you can go to extension manager ? and you can install theme or what
not? well i downloaded a bunch of stuff that i can see in the tab next to
that one you know "installed" how do i put those to use ? i dont see none
of those installed things active nor being used, i downloaded themes for a
more dark look and healthier to my eyes and nothing no effect on my ide
what so ever i closed and re-open and no changes taken place

Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by quasto** [comment]
Hi @FrankOcean11,
from the current version (0.0.3) extensions manager is enabled and you can install Brackets extensions such as Brackets themes. At the moment the gui that you can use to manage themes is disabled because we are working on a better integration with ArduinoStudio. We plan to release also this features in the next version (0.0.4). This features will be available from the menu View -> Themes such as in Brackets.
Regards

**Comment by FrankOcean11** [comment]
ahhhh ic, ithought something was wrong ?! well glad to know it was not me
doing something wrong WELL guess i have no choice but to use the regular
ide for now but i will like to NOT use that old regular ide and start using
A.S thanks for your contribution and help .

Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by quasto** [comment]
thank you @FrankOcean11 for reporting issue and for your patience. We hope to make your development process easier and more pleasant with Arduino Studio.
thanks again
regards

**Comment by sebba** [comment]
Hi @FrankOcean11 .
I'm happy to inform you that we have solved your issue.
Thanks again.

We will release in the coming days the new Arduino Studio (0.0.4) with your fix.
Stay tuned!

Sebba

**Comment by FrankOcean11** [comment]
nice, cant wait, let me know

Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by sebba** [comment]
Hi @FrankOcean11 
have you seen the new release? ;)
http://labs.arduino.org/Arduino+Studio#Try_it_

**Comment by FrankOcean11** [comment]
sure did no, thanks for pointing it out, im on it asap
